apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-hello-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-hello-pod
  template:
    metadata:
      labels:
        app: flask-hello-pod
    spec:
      containers:
        - name: flask-hello-container
          image: flask-hello:latest # use local image with tag
          imagePullPolicy: IfNotPresent # change default to using local image
          ports:
            - containerPort: 5000 # set internal pod's port, mapping to targetPort in Service. Must match the port of app is listening on, e.g. app.run(port=5000) in the flask app.

# Pod/Container
#    Flask app listens on 5000
#    |
#    v
# Kubernetes containerPort: 5000
#    |
#    v
# Service targetPort: 5000
#    |
#    v
# Service port: 5000 or NodePort: 30080 (external)


