apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service
spec:
  type: LoadBalancer
  selector:
    app: flask-hello-pod
  ports:
    - protocol: TCP
      port: 5000        # This Service's internal port inside the cluster
      targetPort: 5000  # port of the pod container of the Deployment, where this Service forwards traffic to. In the Deployment, the Flask contains listens on this port for traffic forwarded by this Service.
