apiVersion: v1
kind: Service
metadata:
  name: flask-hello-service
spec:
  type: NodePort
  selector:
    app: flask-hello-pod
  ports:
    - protocol: TCP
      port: 5000        # This Service's internal port inside the cluster
      targetPort: 5000  # port of the pod container of the Deployment, where this Service forwards traffic to. In the Deployment, the Flask contains listens on this port for traffic forwarded by this Service.
      nodePort: 30080   # port on the nodeâ€™s network interface exposed to the outside world. access your Flask app from outside the cluster using http://<node-ip>:30080

#External request -> Node IP:nodePort (30080)
#                     |
#                     v
#Service port (5000)
#                     |
#                     v
#Pod container port (5000)
